### ISSUE TITLE
Vim, Python, Data Science.

### ISSUE THREAD

**Issue by Copser** [makaimc/fullstackpython.com#53]
Hello I have been reading your article about how to learn and setup vim for python.
I have found some great solution for setup and learning vim for python and framework around it (Django, Flask, Pyramid, etc ), but is it possible to setup it for Data Science.
I suppose coding would not be a problem,  but what about visualizing, is there some libraries I can install.
Thank You.

**Comment by makaimc** [comment]
Unfortunately I'm still new to data analysis and visualization with Python. My recommendation would be to download [Anaconda](http://continuum.io/downloads). That'll include pandas, numpy, scipy, etc. Start using those libraries and search for tutorials on them. I'm hoping to set up pages for data science over the next few months but it'll be slower for me than the web development topics since I'm not as familiar with them. Sorry I can't be of greater help there!

**Comment by Copser** [comment]
No problem @makaimc, I will be happy to read the post you will make on Data Science, till them I am going to explore whit vim, and anaconda.
Thank you ~:)
